[project]
authors = ["Ruben Arts <ruben.arts@hotmail.com>"]
channels = ["https://prefix.dev/conda-forge"]
description = "benchmarking improvements"
name = "bench-improvements"
platforms = ["osx-arm64", "linux-64", "osx-64",  "win-64"]

[feature.python.dependencies]
python = "3.13"

[feature.extreme.dependencies]
rust = "1.82"
scipy = "1.14.1"
scikit-learn = "1.6.0"


[dependencies]
hyperfine = "1.19.0"
jupyterlab = "*"
pandas = ">=2.2.3,<3"
matplotlib = ">=3.10.0,<4"
ipywidgets = ">=8.1.5,<9"
pixi-kernel = ">=0.6.0,<0.7"
ipykernel = ">=6.29.5,<7"

[tasks]
bench-cached-install = "hyperfine --warmup 1 -p 'pixi clean' 'pixi install -e only-python' 'pixi install -e 50k-files' -r 5 --export-json result-cached-install.json"
report = "python generate_report.py"

[environments]
only-python = { features = ["python"], no-default-feature = true }
50k-files = { features = ["extreme"], no-default-feature = true }
