name: Benchmark
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest, macos-13]
        pixi_version: [0.39.2, 0.39.4]
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: simple python extreme
          cache: false
      - run: |
          pixi run -e simple bench
          pixi run -e python bench
          pixi run -e extreme bench
