name: Benchmark
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest, macos-13]
        pixi_version: [v0.39.2, v0.39.3, v0.39.4]
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: ${{ matrix.pixi_version }}
          cache: false
      - run: |
          pixi run bench
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-${{ matrix.pixi_version }}-bench-results.json
          path: result.json
